colleges = [

'National Institute of Technology, Kurukshetra' ,
'National Institute of Technology Raipur' ,
'National Institute of Technology, Rourkela' ,
'National Institute of Technology Calicut' ,
'Indian Institute of Engineering Science and Technology, Shibpur' ,
'National Institute of Technology Delhi' ,
'National Institute of Technology, Rourkela' ,
'National Institute of Technology, Tiruchirappalli' ,
'Maulana Azad National Institute of Technology Bhopal' ,
'National Institute of Technology Hamirpur' ,
'Birla Institute of Technology, Mesra,  Ranchi' ,
'National Institute of Technology, Silchar' ,
'Visvesvaraya National Institute of Technology,Nagpur' ,
'National Institute of Technology Durgapur' ,
'National Institute of Technology, Uttarakhand' ,
'Malaviya National Institute of Technology Jaipur' ,
'Motilal Nehru National Institute of TechnologyAllahabad' ,
'National Institute of Technology, Tiruchirappalli' ,
'National Institute of Technology Patna' ,
'National Institute of Technology Karnataka, Surathkal' ,
'National Institute of Technology Calicut' ,
'Sardar Vallabhbhai National Institute of Technology, Surat' ,
'National Institute of Technology Raipur' ,
'Indian Institute of Information Technology Lucknow' ,
'Punjab Engineering College, Chandigarh' ,
'Visvesvaraya National Institute of Technology, Nagpur' ,
'National Institute of Technology, Warangal' ,
'National Institute of Technology, Andhra Pradesh' ,
'Indian Institute of Engineering Science and Technology, Shibpur' ,
'National Institute of Technology, Jamshedpur' ,
'Malaviya National Institute of Technology Jaipur' ,
'Dr. B R Ambedkar National Institute of Technology, Jalandhar' ,
'National Institute of Technology, Kurukshetra' ,
'National Institute of Technology Puducherry' ,
'University of Hyderabad' ,
'Maulana Azad National Institute of TechnologyBhopal' ,
'National Institute of Technology Goa' ,
'Pt. Dwarka Prasad Mishra Indian Institute ofInformation Technology, Design & Manufacture Jabalpur' ,
'Indian Institute of Engineering Science andTechnology, Shibpur' ,
'National Institute of Technology Delhi' ,
'National Institute of Technology, Warangal' ,
'National Institute of Technology Hamirpur' ,
'Indian Institute of Information Technology, Design &Manufacturing, Kancheepuram' ,
'Atal Bihari Vajpayee Indian Institute of Information Technology& Management Gwalior' ,
'National Institute of Technology Meghalaya' ,
'Indian Institute of Information Technology Lucknow' ,
'National Institute of Technology Raipur' ,
'National Institute of Technology, Rourkela' ,
'National Institute of Technology Durgapur' ,
'National Institute of Technology, Kurukshetra' ,
'National Institute of Technology, Tiruchirappalli' ,
'Sardar Vallabhbhai National Institute of Technology,Surat' ,
'National Institute of Technology Calicut' ,
'National Institute of Technology  Agartala' ,
'National Institute of Technology Karnataka, Surathkal' ,
'National Institute of Technology, Silchar' ,
'Birla Institute of Technology, Mesra,  Ranchi' ,
'National Institute of Technology, Rourkela' ,
'Dr. B R Ambedkar National Institute of Technology,Jalandhar' ,
'National Institute of Technology, Rourkela' ,
'Indian Institute of Engineering Science andTechnology, Shibpur' ,
'National Institute of Technology, Jamshedpur' ,
'Maulana Azad National Institute of TechnologyBhopal' ,
'National Institute of Technology Goa' ,
'Punjab Engineering College, Chandigarh' ,
'Motilal Nehru National Institute of TechnologyAllahabad' ,
'National Institute of Technology Puducherry' ,
'National Institute of Technology Hamirpur' ,
'National Institute of Technology, Tiruchirappalli' ,
'Motilal Nehru National Institute of TechnologyAllahabad' ,
'National Institute of Technology Durgapur' ,
'National Institute of Technology, Uttarakhand' ,
'Jawaharlal Nehru University, Delhi' ,
'Atal Bihari Vajpayee Indian Institute of Information Technology& Management Gwalior' ,
'National Institute of Technology Patna' ,
'National Institute of Technology, Andhra Pradesh' ,
'Indian Institute of Information Technology(IIIT)Kilohrad, Sonepat, Haryana' ,
'International Institute of Information Technology,Naya Raipur' ,
'National Institute of Technology Hamirpur' ,
'Malaviya National Institute of Technology Jaipur' ,
'National Institute of Technology Goa' ,
'National Institute of Technology, Jamshedpur' ,
'Indian Institute of Information Technology Guwahati' ,
'Punjab Engineering College, Chandigarh' ,
'Indian Institute of Information Technology Srirangam,Tiruchirappalli' ,
'National Institute of Technology, Rourkela' ,
'International Institute of Information Technology,Naya Raipur' ,
'Dr. B R Ambedkar National Institute of Technology,Jalandhar' ,
'Indian institute of information technology, Raichur,Karnataka' ,
'National Institute of Technology Raipur' ,
'National Institute of Technology Hamirpur' ,
'Birla Institute of Technology, Mesra,  Ranchi' ,
'Indian Institute of Engineering Science andTechnology, Shibpur' ,
'International Institute of Information Technology,Bhubaneswar' ,
'National Institute of Technology, Warangal' ,
'Motilal Nehru National Institute of TechnologyAllahabad' ,
'National Institute of Technology Karnataka, Surathkal' ,
'Indian Institute of Information Technology Surat' ,
'National Institute of Technology Calicut' ,
'Indian Institute of Information Technology, Design &Manufacturing, Kancheepuram' ,
'Indian Institute of Information Technology (IIIT)Kota,Rajasthan' ,
'National Institute of Technology, Srinagar' ,
'Visvesvaraya National Institute of Technology,Nagpur' ,
'National Institute of Technology Calicut' ,
'National Institute of Technology, Silchar' ,
'Indian Institute of Information Technology (IIIT) Pune' ,
'Pt. Dwarka Prasad Mishra Indian Institute ofInformation Technology, Design & Manufacture Jabalpur' ,
'Sardar Vallabhbhai National Institute of Technology,Surat' ,
'National Institute of Technology Sikkim' ,
'Indian Institute of Information Technology, Design &Manufacturing, Kancheepuram' ,
'National Institute of Technology, Rourkela' ,
'Visvesvaraya National Institute of Technology,Nagpur' ,
'National Institute of Technology Raipur' ,
'Punjab Engineering College, Chandigarh' ,
'Indian Institute of Engineering Science andTechnology, Shibpur' ,
'National Institute of Technology, Rourkela' ,
'Malaviya National Institute of Technology Jaipur' ,
'National Institute of Technology  Agartala' ,
'National Institute of Technology Puducherry' ,
'Indian Institute of Information Technology(IIIT)Kilohrad, Sonepat, Haryana' ,
'National Institute of Technology Arunachal Pradesh' ,
'National Institute of Technology Patna' ,
'National Institute of Technology, Silchar' ,
'International Institute of Information Technology,Bhubaneswar' ,
'Maulana Azad National Institute of TechnologyBhopal' ,
'Indian Institute of Information Technology (IIIT), SriCity, Chittoor' ,
'National Institute of Technology, Kurukshetra' ,
'Jawaharlal Nehru University, Delhi' ,
'International Institute of Information Technology,Bhubaneswar' ,
'Sardar Vallabhbhai National Institute of Technology,Surat' ,
'National Institute of Technology, Manipur' ,
'Birla Institute of Technology, Mesra,  Ranchi' ,
'National Institute of Technology, Mizoram' ,
'Maulana Azad National Institute of TechnologyBhopal' ,
'National Institute of Technology Puducherry' ,
'National Institute of Technology, Uttarakhand' ,
'National Institute of Technology Nagaland' ,
'National Institute of Technology, Uttarakhand' ,
'National Institute of Technology Durgapur' ,
'National Institute of Technology Meghalaya' ,
'National Institute of Technology Patna' ,
'National Institute of Technology Karnataka, Surathkal' ,
'National Institute of Technology, Silchar' ,
'National Institute of Technology  Agartala' ,
'National Institute of Technology Durgapur' ,
'National Institute of Technology Calicut' ,
'Indian Institute of Information Technology(IIIT),Vadodara, Gujrat' ,
'Dr. B R Ambedkar National Institute of Technology,Jalandhar' ,
'Indian Institute of Information Technology Bhopal' ,
'National Institute of Technology, Andhra Pradesh' ,
'National Institute of Technology, Warangal' ,
'Indian Institute of Information Technology (IIIT) Pune' ,
'National Institute of Technology, Srinagar' ,
'National Institute of Technology, Andhra Pradesh' ,
'Indian Institute of Information Technology Srirangam,Tiruchirappalli' ,
'Indian Institute of Information Technology, Design & Manufacturing, Kancheepuram' ,
'National Institute of Technology  Agartala' ,
'Indian Institute of Information Technology(IIIT) Una,Himachal Pradesh' ,
'National Institute of Technology, Rourkela' ,
'National Institute of Technology  Agartala' ,
'International Institute of Information Technology,Naya Raipur' ,
'Indian Institute of Information Technology (IIIT), SriCity, Chittoor' ,
'National Institute of Technology, Manipur' ,
'National Institute of Technology, Jamshedpur' ,
'National Institute of Technology Durgapur' ,
'Indian Institute of Information Technology(IIIT),Vadodara, Gujrat' ,
'Dr. B R Ambedkar National Institute of Technology,Jalandhar' ,
'Indian Institute of Information Technology (IIIT)Nagpur' ,
'National Institute of Technology Arunachal Pradesh' ,
'National Institute of Technology Hamirpur' ,
'Indian Institute of Information Technology, Design &Manufacturing, Kancheepuram' ,
'National Institute of Technology, Rourkela' ,
'National Institute of Technology Meghalaya' ,
'National Institute of Technology Hamirpur' ,
'National Institute of Technology, Rourkela' ,
'National Institute of Technology Sikkim' ,
'Indian Institute of Information Technology Guwahati' ,
'Indian Institute of Information Technology (IIIT)Kota,Rajasthan' ,
'National Institute of Technology Goa' ,
'National Institute of Technology, Rourkela' ,
'National Institute of Technology Raipur' ,
'National Institute of Technology Nagaland' ,
'Indian Institute of Information Technology Design &Manufacturing Kurnool, Andhra Pradesh' ,
'National Institute of Technology, Kurukshetra' ,
'Dr. B R Ambedkar National Institute of Technology,Jalandhar' ,
'National Institute of Technology Puducherry' ,
'Indian Institute of Information Technology (IIIT)Ranchi' ,
'National Institute of Technology Meghalaya' ,
'Indian Institute of Information Technology Bhopal' ,
'Indian Institute of Information Technology(IIIT)Kottayam' ,
'Indian Institute of Information Technology, Design & Manufacturing, Kancheepuram' ,
'National Institute of Technology, Rourkela' ,
'Visvesvaraya National Institute of Technology,Nagpur' ,
'National Institute of Technology, Mizoram' ,
'National Institute of Technology Calicut' ,
'Indian Institute of Information Technology(IIIT) Una,Himachal Pradesh' ,
'National Institute of Technology Raipur' ,
'National Institute of Technology, Rourkela' ,
'Indian Institute of Information Technology(IIIT)Dharwad' ,
'National Institute of Technology Calicut' ,
'National Institute of Technology Patna' ,
'Indian Institute of Information Technology Surat' ,
'National Institute of Technology, Srinagar' ,
'National Institute of Technology, Silchar' ,
'Pt. Dwarka Prasad Mishra Indian Institute ofInformation Technology, Design & Manufacture Jabalpur' ,
'Indian Institute of Information Technology(IIIT)Kalyani, West Bengal' ,
'National Institute of Technology, Uttarakhand' ,
'Central University of Rajasthan, Rajasthan' ,
'International Institute of Information Technology,Bhubaneswar' ,
'Punjab Engineering College, Chandigarh' ,
'Visvesvaraya National Institute of Technology,Nagpur' ,
'Malaviya National Institute of Technology Jaipur' ,
'National Institute of Technology Arunachal Pradesh' ,
'Indian Institute of Information Technology Bhopal' ,
'Sardar Vallabhbhai National Institute of Technology,Surat' ,
'Indian Institute of Information Technology (IIIT)Nagpur' ,
'National Institute of Technology, Andhra Pradesh' ,
'Birla Institute of Technology, Mesra,  Ranchi' ,
'Pondicherry Engineering College, Puducherry' ,
'National Institute of Technology, Rourkela' ,
'National Institute of Technology, Manipur' ,
'National Institute of Technology Sikkim' ,
'Indian Institute of Engineering Science andTechnology, Shibpur' ,
'Birla Institute of Technology, Mesra,  Ranchi' ,
'Indian Institute of Information Technology Design &Manufacturing Kurnool, Andhra Pradesh' ,
'Maulana Azad National Institute of TechnologyBhopal' ,
'National Institute of Technology, Manipur' ,
'National Institute of Technology, Rourkela' ,
'National Institute of Technology, Jamshedpur' ,
'National Institute of Technology Hamirpur' ,
'National Institute of Technology  Agartala' ,
'National Institute of Technology, Andhra Pradesh' ,
'Institute of Infrastructure, Technology, Research andManagement-Ahmedabad' ,
'National Institute of Technology Sikkim' ,
'J.K. Institute of Applied Physics & Technology,Department of Electronics & Communication, University of Allahabad- Allahabad' ,
'Sardar Vallabhbhai National Institute of Technology,Surat' ,
'Indian Institute of Information Technology(IIIT)Dharwad' ,
'Indian Institute of Information Technology, Agartala' ,
'National Institute of Technology, Rourkela' ,
'Motilal Nehru National Institute of TechnologyAllahabad' ,
'National Institute of Technology, Jamshedpur' ,
'Indian Institute of Information Technology (IIIT)Ranchi' ,
'National Institute of Technology  Agartala' ,
'International Institute of Information Technology,Bhubaneswar' ,
'Indian Institute of Information Technology Bhagalpur' ,
'Indian Institute of Information Technology(IIIT) Una,Himachal Pradesh' ,
'National Institute of Technology Durgapur' ,
'National Institute of Technology  Agartala' ,
'National Institute of Technology Arunachal Pradesh' ,
'National Institute of Technology, Rourkela' ,
'Punjab Engineering College, Chandigarh' ,
'National Institute of Technology  Agartala' ,
'National Institute of Technology Nagaland' ,
'Indian Institute of Information Technology  Manipur' ,
'National Institute of Technology, Srinagar' ,
'National Institute of Technology Meghalaya' ,
'Indian Institute of Information Technology, Design &Manufacturing, Kancheepuram' ,
'Institute of Infrastructure, Technology, Research andManagement-Ahmedabad' ,
'Indian Institute of Information Technology, Design &Manufacturing, Kancheepuram' ,
'National Institute of Technology, Srinagar' ,
'National Institute of Technology, Mizoram' ,
'Indian Institute of Engineering Science andTechnology, Shibpur' ,
'Dr. B R Ambedkar National Institute of Technology,Jalandhar' ,
'National Institute of Technology Raipur' ,
'National Institute of Technology Patna' ,
'Central University of Rajasthan, Rajasthan' ,
'National Institute of Technology Sikkim' ,
'Indian Institute of Engineering Science andTechnology, Shibpur' ,
'Indian Institute of Information Technology Bhagalpur' ,
'Dr. B R Ambedkar National Institute of Technology,Jalandhar' ,
'National Institute of Technology, Mizoram' ,
'National Institute of Technology, Manipur' ,
'Indian Institute of Information Technology Design &Manufacturing Kurnool, Andhra Pradesh' ,
'National Institute of Technology  Agartala' ,
'National Institute of Technology Arunachal Pradesh' ,
'National Institute of Technology, Andhra Pradesh' ,
'National Institute of Technology Patna' ,
'J.K. Institute of Applied Physics & Technology,Department of Electronics & Communication, University of Allahabad- Allahabad' ,
'National Institute of Technology Raipur' ,
'Indian Institute of Information Technology, Design &Manufacturing, Kancheepuram' ,
'Assam University, Silchar' ,
'National Institute of Technology Durgapur' ,
'Sant Longowal Institute of Engineering andTechnology' ,
'National Institute of Technology Nagaland' ,
'National Institute of Technology Nagaland' ,
'Pondicherry Engineering College, Puducherry' ,
'Birla Institute of Technology, Mesra,  Ranchi' ,
'National Institute of Technology, Andhra Pradesh' ,
'Indian Institute of Information Technology  Manipur' ,
'Institute of Infrastructure, Technology, Research andManagement-Ahmedabad' ,
'National Institute of Technology Raipur' ,
'Dr. B R Ambedkar National Institute of Technology,Jalandhar' ,
'Indian Institute of Information Technology Bhagalpur' ,
'Birla Institute of Technology, Mesra,  Ranchi' ,
'National Institute of Technology, Mizoram' ,
'National Institute of Electronics and Information Technology,Aurangabad (Maharashtra)' ,
'National Institute of Technology Nagaland' ,
'National Institute of Technology Durgapur' ,
'National Institute of Technology, Srinagar' ,
'National Institute of Technology Durgapur' ,
'National Institute of Technology, Srinagar' ,
'Punjab Engineering College, Chandigarh' ,
'National Institute of Technology  Agartala' ,
'Sardar Vallabhbhai National Institute of Technology,Surat' ,
'Institute of Technology, Guru GhasidasVishwavidyalaya (A Central University), Bilaspur, (C.G.)' ,
'Birla Institute of Technology, Mesra,  Ranchi' ,
'Pondicherry Engineering College, Puducherry' ,
'National Institute of Technology  Agartala' ,
'Sant Longowal Institute of Engineering andTechnology' ,
'National Institute of Technology, Rourkela' ,
'School of Engineering, Tezpur University, Napaam,Tezpur' ,
'National Institute of Technology Patna' ,
'Gurukula Kangri Vishwavidyalaya, Haridwar' ,
'National Institute of Technology Raipur' ,
'Central institute of Technology Kokrajar, Assam' ,
'National Institute of Technology, Srinagar' ,
'HNB Garhwal University Srinagar (Garhwal)' ,
'Assam University, Silchar' ,
'Central institute of Technology Kokrajar, Assam' ,
'National Institute of Technology  Agartala' ,
'Sant Longowal Institute of Engineering andTechnology' ,
'Pondicherry Engineering College, Puducherry' ,
'Shri Mata Vaishno Devi University, Katra, Jammu &Kashmir' ,
'HNB Garhwal University Srinagar (Garhwal)' ,
'Mizoram University, Aizawl' ,
'Institute of Technology, Guru GhasidasVishwavidyalaya (A Central University), Bilaspur, (C.G.)' ,
'Mizoram University, Aizawl' ,
'Institute of Technology, Guru GhasidasVishwavidyalaya (A Central University), Bilaspur, (C.G.)' ,
'School of Engineering, Tezpur University, Napaam,Tezpur' ,
'Ghani Khan Choudhary Institute of Engineering andTechnology, Malda, West Bengal' ,
'HNB Garhwal University Srinagar (Garhwal)' ,
'Central institute of Technology Kokrajar, Assam' ,
'HNB Garhwal University Srinagar (Garhwal)' ,
'School of Engineering, Tezpur University, Napaam,Tezpur' ,
'Central institute of Technology Kokrajar, Assam' ,
'Ghani Khan Choudhary Institute of Engineering andTechnology, Malda, West Bengal' ,
'School of Engineering, Tezpur University, Napaam,Tezpur' ,
'Gurukula Kangri Vishwavidyalaya, Haridwar' ,
'National Institute of Foundry & Forge Technology,Hatia, Ranchi' ,
'Mizoram University, Aizawl' ,
'Sant Longowal Institute of Engineering andTechnology' ,
'Mizoram University, Aizawl' ,
'Institute of Technology, Guru GhasidasVishwavidyalaya (A Central University), Bilaspur, (C.G.)' ,
'Gurukula Kangri Vishwavidyalaya, Haridwar' ,
'School of Engineering, Tezpur University, Napaam,Tezpur' ,
'Sant Longowal Institute of Engineering andTechnology' ,
'Shri Mata Vaishno Devi University, Katra, Jammu &Kashmir' ,
'Institute of Technology, Guru GhasidasVishwavidyalaya (A Central University), Bilaspur, (C.G.)' ,
'Institute of Technology, Guru GhasidasVishwavidyalaya (A Central University), Bilaspur, (C.G.)' ,
'HNB Garhwal University Srinagar (Garhwal)' ,
'Gurukula Kangri Vishwavidyalaya, Haridwar' ,
'Shri Mata Vaishno Devi University, Katra, Jammu &Kashmir' ,
'Sant Longowal Institute of Engineering andTechnology' ,
'Mizoram University, Aizawl' ,
'National Institute of Foundry & Forge Technology,Hatia, Ranchi' ,
'Assam University, Silchar' ,
'Shri Mata Vaishno Devi University, Katra, Jammu &Kashmir' ,
'Shri Mata Vaishno Devi University, Katra, Jammu &Kashmir' ,
'Central institute of Technology Kokrajar, Assam' ,
'Indian Institute of Carpet Technology,  Bhadohi' ,
'Institute of Technology, Guru Ghasidas Vishwavidyalaya (A Central University), Bilaspur, (C.G.)' ,
'Sant Longowal Institute of Engineering andTechnology' ,
'Ghani Khan Choudhary Institute of Engineering andTechnology, Malda, West Bengal' ,
'School of Engineering, Tezpur University, Napaam, Tezpur' ,
'National Institute of Food Technology Entrepreneurship and Management, Sonepat, Haryana' ,
]


Streams = [
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Electrical and Electronics Engineering (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Electronics and Instrumentation Engineering (4 Years, Bachelor ofTechnology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Computer Science and Engineering (5 Years, Bachelor and Master ofTechnology (Dual Degree))' ,
'Information Technology (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Electrical and Electronics Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Electrical Engineering (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Instrumentation and Control Engineering (4 Years, Bachelor ofTechnology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Chemical Engineering (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Electrical Engineering (4 Years, Bachelor of Technology)' ,
'Information Technology (4 Years, Bachelor of Technology)' ,
'Computer Science (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Chemical Engineering (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Aerospace Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Electrical Engineering (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Computer Science (5 Years, Integrated Master of Technology)' ,
'Electrical Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Information Technology (4 Years, Bachelor of Technology)' ,
'Electrical and Electronics Engineering (4 Years, Bachelor of Technology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Integrated B. Tech.(IT) and M. Tech (IT) (5 Years, Integrated B. Tech. andM. Tech. /MBA)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Information Technology (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Physics (5 Years, Integrated Master of Science)' ,
'Electrical Engineering (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Metallurgical and Materials Engineering (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Engineering Physics (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Electrical Engineering (4 Years, Bachelor of Technology)' ,
'Chemical Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Telecommunication Engineering (4 Years, Bachelor ofTechnology)' ,
'Electrical Engineering (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Electrical and Electronics Engineering (4 Years, Bachelor of Technology)' ,
'Aerospace Engineering (4 Years, Bachelor of Technology)' ,
'Chemical Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Electrical Engineering (4 Years, Bachelor of Technology)' ,
'Production Engineering (4 Years, Bachelor of Technology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Computer Science and Engineering (5 Years, Bachelor and Master ofTechnology (Dual Degree))' ,
'Integrated B. Tech.(IT) and MBA (5 Years, Integrated B. Tech. and M. Tech./MBA)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Data Science and Artiﬁcial Intelligence (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (5 Years, Bachelor and Masterof Technology (Dual Degree))' ,
'Chemical Engineering (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Electrical Engineering (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Chemical Engineering (5 Years, Bachelor and Master of Technology (DualDegree))' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Electrical Engineering (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Electrical and Electronics Engineering (4 Years, Bachelor of Technology)' ,
'Electrical Engineering (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Metallurgical and Materials Engineering (4 Years, Bachelor of Technology)' ,
'Production and Industrial Engineering (4 Years, Bachelor of Technology)' ,
'Metallurgical and Materials Engineering (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Chemical Engineering (4 Years, Bachelor of Technology)' ,
'Electrical Engineering (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor of Technology)' ,
'Chemical Engineering (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (5 Years, Bachelor and Master ofTechnology (Dual Degree))' ,
'Mathematics (5 Years, Integrated Master of Science)' ,
'Chemical Engineering (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Metallurgical and Materials Engineering (4 Years, Bachelor of Technology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Information Technology (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Electrical Engineering (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Computer Engineering (4 Years, Bachelor of Technology)' ,
'Chemical Engineering (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (5 Years, Bachelor and Masterof Technology (Dual Degree))' ,
'Information Technology (4 Years, Bachelor of Technology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Electrical and Electronics Engineering (4 Years, Bachelor of Technology)' ,
'Electrical and Electronics Engineering (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Mining Engineering  (4 Years, Bachelor of Technology)' ,
'Electronics and Instrumentation Engineering (4 Years, Bachelor ofTechnology)' ,
'Mathematics and Computing (5 Years, Integrated Master of Technology)' ,
'Chemical Engineering (4 Years, Bachelor of Technology)' ,
'Production Engineering (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Electrical and Electronics Engineering (4 Years, Bachelor of Technology)' ,
'Bio Technology (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Information Technology (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'B. Tech. Electronics and Communication Engineering and M. Tech. Electronics andCommunication Engineering with specialization in VLSI Design  (5 Years, Bachelor and Master of Technology (Dual Degree))' ,
'Electrical Engineering (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Mining Engineering  (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Chemical Engineering (5 Years, Bachelor and Master of Technology (DualDegree))' ,
'Information Technology (4 Years, Bachelor of Technology)' ,
'Instrumentation and Control Engineering (4 Years, Bachelor ofTechnology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Bio Technology (4 Years, Bachelor of Technology)' ,
'Electrical and Electronics Engineering (4 Years, Bachelor of Technology)' ,
'Chemical Engineering (4 Years, Bachelor of Technology)' ,
'Metallurgical and Materials Engineering (5 Years, Bachelor and Master ofTechnology (Dual Degree))' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Industrial Design (4 Years, Bachelor of Technology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Computer Engineering (4 Years, Bachelor of Technology)' ,
'Production and Industrial Engineering (4 Years, Bachelor of Technology)' ,
'Chemical Engineering (4 Years, Bachelor of Technology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Information Technology (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'B. Tech. Electronics and Communication Engineering and  M. Tech.Electronics and Communication Engineering with specialization in Communication Systems Design (5 Years, Bachelor and Master of Technology (Dual Degree))' ,
'Mining Engineering (5 Years, Bachelor and Master of Technology (DualDegree))' ,
'Metallurgical and Materials Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Materials Science and Engineering (4 Years, Bachelor of Technology)' ,
'Information Technology (4 Years, Bachelor of Technology)' ,
'Chemical Engineering (4 Years, Bachelor of Technology)' ,
'Chemistry (5 Years, Integrated Master of Science)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Bio Technology (4 Years, Bachelor of Technology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Telecommunication Engineering (4 Years, Bachelor ofTechnology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Mining Engineering  (4 Years, Bachelor of Technology)' ,
'Metallurgical and Materials Engineering (4 Years, Bachelor of Technology)' ,
'Electrical Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Physics (5 Years, Integrated Master of Science)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Bio Medical Engineering (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Chemical Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering with specialization in Design andManufacturing (4 Years, Bachelor of Technology)' ,
'Materials Science and Metallurgical Engineering (4 Years, Bachelor ofTechnology)' ,
'Electrical Engineering (4 Years, Bachelor of Technology)' ,
'Ceramic Engineering (4 Years, Bachelor of Technology)' ,
'Production and Industrial Engineering (4 Years, Bachelor of Technology)' ,
'Materials Science and Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Instrumentation Engineering (4 Years, Bachelor ofTechnology)' ,
'Chemical Engineering (4 Years, Bachelor of Technology)' ,
'Electrical Engineering (4 Years, Bachelor of Technology)' ,
'Electrical and Electronics Engineering (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Mathematics (5 Years, Integrated Master of Science)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Food Process Engineering (4 Years, Bachelor of Technology)' ,
'Bio Technology (4 Years, Bachelor of Technology)' ,
'Metallurgical and Materials Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Electrical and Electronics Engineering (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Metallurgical and Materials Engineering (4 Years, Bachelor of Technology)' ,
'Engineering Physics (5 Years, Bachelor and Master of Technology (DualDegree))' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Ceramic Engineering and M.Tech Industrial Ceramic (5 Years, Bachelor andMaster of Technology (Dual Degree))' ,
'Production and Industrial Engineering (4 Years, Bachelor of Technology)' ,
'Chemical Engineering (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Electrical Engineering (4 Years, Bachelor of Technology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'B. Tech. Mechanical Engineering and M. Tech. in Mechanical Engineeringwith specialization in Product Design (5 Years, Bachelor and Master of Technology (Dual Degree))' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Smart Manufacturing (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Mining Engineering  (4 Years, Bachelor of Technology)' ,
'Industrial and Production Engineering (4 Years, Bachelor of Technology)' ,
'Metallurgical and Materials Engineering (4 Years, Bachelor of Technology)' ,
'Physics (5 Years, Integrated Master of Science)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Metallurgy and Materials Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Bio Technology (4 Years, Bachelor of Technology)' ,
'Electrical and Electronics Engineering (4 Years, Bachelor of Technology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering with specialization in Design and Manufacturing (4 Years,Bachelor of Technology)' ,
'Physics (5 Years, Bachelor of Science and Master of Science (Dual Degree))' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Metallurgical and Materials Engineering (4 Years, Bachelor of Technology)' ,
'Mathematics (5 Years, Integrated Master of Science)' ,
'Electronics and Communication Engineering (4 Years, Bachelor of Technology)' ,
'Mining Engineering  (4 Years, Bachelor of Technology)' ,
'B. Tech. Mechanical Engineering and M. Tech. Mechanical Engineeringwith specialization in Advanced Manufacturing (5 Years, Bachelor and Master of Technology (Dual Degree))' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Bio Technology (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Instrumentation Engineering (4 Years, Bachelor ofTechnology)' ,
'Electrical and Electronics Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Production Engineering (4 Years, Bachelor of Technology)' ,
'Bio Technology (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Bio Technology (4 Years, Bachelor of Technology)' ,
'Textile Technology (4 Years, Bachelor of Technology)' ,
'Mechatronics Engineering (4 Years, Bachelor of Technology)' ,
'Chemical Engineering (Plastic and Polymer) (4 Years, Bachelor ofTechnology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Electronics System Engineering (4 Years, Bachelor of Technology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Chemistry (5 Years, Integrated Master of Science)' ,
'Chemical Engineering (4 Years, Bachelor of Technology)' ,
'Biotechnology (5 Years, Bachelor and Master of Technology (Dual Degree))' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Materials and Metallurgical Engineering (4 Years, Bachelor of Technology)' ,
'Production Engineering (4 Years, Bachelor of Technology)' ,
'Chemistry (5 Years, Integrated Master of Science)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Bio Technology (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Biotechnology and Biochemical Engineering (4 Years, Bachelor ofTechnology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Life Science (5 Years, Integrated Master of Science)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Chemistry (5 Years, Integrated Master of Science)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Bio Medical Engineering (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Metallurgical and Materials Engineering (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Chemistry (5 Years, Bachelor of Science and Master of Science (DualDegree))' ,
'Electrical Engineering (4 Years, Bachelor of Technology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Computer Science and Engineering (4 Years, Bachelor of Technology)' ,
'Information Technology (4 Years, Bachelor of Technology)' ,
'Computer Engineering (4 Years, Bachelor of Technology)' ,
'Information Technology (4 Years, Bachelor of Technology)' ,
'Information Technology (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Electrical Engineering (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Instrumentation Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Electrical Engineering (4 Years, Bachelor of Technology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Metallurgy and Materials Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Electrical Engineering (4 Years, Bachelor of Technology)' ,
'Chemical Engineering (4 Years, Bachelor of Technology)' ,
'Electrical Engineering (4 Years, Bachelor of Technology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Chemical Engineering (4 Years, Bachelor of Technology)' ,
'Electronics and Communication Engineering (4 Years, Bachelor ofTechnology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Electrical and Instrumentation Engineering (4 Years, Bachelor ofTechnology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Electrical Engineering (4 Years, Bachelor of Technology)' ,
'Instrumentation and Control Engineering (4 Years, Bachelor ofTechnology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Manufacturing Engineering (4 Years, Bachelor of Technology)' ,
'Agricultural Engineering (4 Years, Bachelor of Technology)' ,
'Mechanical Engineering (4 Years, Bachelor of Technology)' ,
'Civil Engineering (4 Years, Bachelor of Technology)' ,
'Food Engineering  and Technology (4 Years, Bachelor of Technology)' ,
'Carpet  and Textile Technology (4 Years, Bachelor of Technology)' ,
'Industrial and Production Engineering (4 Years, Bachelor of Technology)' ,
'Food Technology (4 Years, Bachelor of Technology)' ,
'Food Technology (4 Years, Bachelor of Technology)' ,
'Food Engineering  and Technology (4 Years, Bachelor of Technology)' ,
'Food Technology and Management (4 Years, Bachelor of Technology)' ,
]

"""import itertools  


i = 1
for (colle , stre) in zip(colleges,Streams):
	print(colle, stre)
	i += 1
print(i)"""